[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["nanoworks*"]

[tool.setuptools.package-data]
"nanoworks" = ["examples/*", "examples/**/*"]

[project]
name = "nanoworks"
version = "26.8.0"
description = " Nanoworks is a unified, high-level Python orchestrator for conducting DFT, MD and ML calculations"
readme = "README.md"
requires-python = ">=3.8" 
license = { text = "MIT" }
authors = [{name = "Sefer Bora Lisesivdin" }, {name = "Beyza Sarikavak-Lisesivdin"}]
dependencies = [
    "ase>=3.22.0",
    "spglib",
    "docutils"
]

[project.optional-dependencies]

gpaw = [
    "gpaw>=26.7.0",
    "elastic",
    "phonopy",
    "pyrapl",
    "pymongo",
    "pandas"
]

qe = [
]

dft = [
    "gpaw>=26.7.0",
    "elastic",
    "phonopy",
    "pyrapl",
    "pymongo",
    "pandas"
]

md = [
    "asap3",
    "kimpy"
]

ml = [
    "torch",
    "mace-torch",
    "chgnet",
    "sevenn"
]

all = [
    "gpaw>=26.7.0",
    "elastic",
    "phonopy",
    "pyrapl",
    "pymongo",
    "pandas",
    "asap3",
    "kimpy",
    "torch",
    "mace-torch",
    "chgnet",
    "sevenn",
    "cython==3.1.3"
]

[project.scripts]
dftsolve = "nanoworks.dftsolve:main"
mdsolve = "nanoworks.mdsolve:main"
mlsolve = "nanoworks.mlsolve:main"
qeconverter = "nanoworks.qeconverter:main"
vaspconverter = "nanoworks.vaspconverter:main"
nanoworks = "nanoworks.cli:main"
